### ISSUE TITLE
Link up /star me reference

### ISSUE THREAD

**Issue by jglovier** [jonrohan/hubot-slack-reactions#1]
The README contains this line:

> A hubot script like /star me except for slack reactions.

If a user isn't familiar with `/star me`, it might be helpful to have a link here to the source for that script just for further context.

**Comment by jglovier** [comment]
...for context, primarily because I bet the amount of people who use Slack and might find this useful far surpasses the amount of people who use Hubot && know what /star me is. FTR I don't even know what /star me does. :smile:

**Comment by jonrohan** [comment]
:heart: fair enough

**Comment by jglovier** [comment]
:metal: :star:
